### ISSUE TITLE
【開発】ブランチ運用について

### ISSUE THREAD

**Issue by TakenokoTech** [tekuppi1/texclient#1]
@pythonissam

急に失礼します。
masterブランチを公開用のブランチにしたいのですが、
現段階でmasterブランチから枝分かれさせすぎると、公開時にバグをマージするリスクが高くなってしまいます。

なので、開発ブランチとテストブランチを分けると、マージによるバグ発生は抑えれると思います。
よかったら検討お願いします。
![default](https://cloud.githubusercontent.com/assets/9033882/18250947/441725d0-73c1-11e6-8a3e-617eb9d41a48.png)

**Comment by pythonissam** [comment]
めっちゃ分かりやすいですね笑
もちろんそうします

**Comment by TakenokoTech** [comment]
@pythonissam 
メンバーに入れてちょ

**Comment by pythonissam** [comment]
@TakenokoPro

多分、僕はただのメンバーなので、

**Comment by pythonissam** [comment]
追加とかできないような。。。

**Comment by TakenokoTech** [comment]
がーーｎ(___;

**Comment by pythonissam** [comment]
笑
そしてすしは今日忙しいので明日追加するよーって言ってたような。。。

**Comment by pythonissam** [comment]
めんぼくないですw

**Comment by TakenokoTech** [comment]
なぬーーー。
あと、インストール手順とかは別ブランチの方がいいよ。
publicで見えちゃってるから。

**Comment by TakenokoTech** [comment]
gulpはnpm install すれば別ブランチに切り替わっても環境が残る設定にしてあるよ。

**Comment by pythonissam** [comment]
ほうほう。参考になりまする

**Comment by pythonissam** [comment]
あるブランチだけ private にするとかできるんですか?

**Comment by TakenokoTech** [comment]
initsettingブランチにREADME.md入れといてdevelopがコミットされたらリベースしてく。
さすがに、publicでもブランチ一個一個は見られないと思うよ。

**Comment by pythonissam** [comment]
むぅぅ。。。でもそれって、developブランチにリベースしちゃったら、次回以降のコミットで、master にマージされちゃうようなことはないんですか?

**Comment by TakenokoTech** [comment]
うん？
developブランチから直接masterにマージすることは無いで。
でも、リベースだと変になるかも(;´･ω･)
![default](https://cloud.githubusercontent.com/assets/9033882/18251773/15bb9b80-73c6-11e6-8690-d1bde275d076.png)

**Comment by TakenokoTech** [comment]
たぶん、リベースコミットじゃなくて、プルしてマージコミットだ

**Comment by TakenokoTech** [comment]
なんか、developブランチに入れとけば良いような気がしてきた・・・

**Comment by pythonissam** [comment]
なるほど、理解ですw すごい理解です

**Comment by pythonissam** [comment]
なるほど、見られないだろうっていう議論ですね

**Comment by TakenokoTech** [comment]
ようは、そういうこと！

**Comment by pythonissam** [comment]
む? む?

**Comment by pythonissam** [comment]
でもそれこそ master の方にいっちゃうような笑

**Comment by pythonissam** [comment]
initsetting の話は超絶理解しました笑

**Comment by pythonissam** [comment]
じゃ上のブランチ、とりあえず作っときますね!

**Comment by TakenokoTech** [comment]
testブランチからdevelop割ってね

**Comment by TakenokoTech** [comment]
メンバーに入りたいよぉぉぉ

**Comment by pythonissam** [comment]
了解でっす。あと数時間待ってくださいw

**Comment by TakenokoTech** [comment]
invisible　なに入れるやつ？？

**Comment by pythonissam** [comment]
なるほど、これってローカルに置いておけばいいですね

**Comment by pythonissam** [comment]
initsetting 的なものだったんですが

**Comment by pythonissam** [comment]
そもそも書くのがよろしくないのなら消しますね

**Comment by TakenokoTech** [comment]
せやな、作るとしてもdevelop#initくらいの階層じゃないと弄り難いね

**Comment by TakenokoTech** [comment]
一旦、developからブランチ切って開発環境整えていくのが良いかな。

**Comment by TakenokoTech** [comment]
http://qiita.com/tamikura@github/items/e7a319afba5f9ca4528a
あと、これもやっといて欲しいな。

**Comment by pythonissam** [comment]
了解でっす

**Comment by pythonissam** [comment]
ほう!

**Comment by TakenokoTech** [comment]
developに開発環境のマージする手前でプルリクくれると嬉しいなぁ

**Comment by pythonissam** [comment]
全部のブランチですよね?

**Comment by TakenokoTech** [comment]
おっす！

**Comment by pythonissam** [comment]
できました!

**Comment by pythonissam** [comment]
もうタスク終了ですね笑

**Comment by TakenokoTech** [comment]
おっけ。クローズしやす。

**Comment by pythonissam** [comment]
Ｏ(≧▽≦)Ｏ ﾜｰｲ♪

**Comment by TakenokoTech** [comment]
ごくろう！
