### ISSUE TITLE
管理者用ダッシュボードの作成

### ISSUE THREAD

**Issue by hatimitusiropp** [tekuppi1/texclient#14]
・ログイン画面
　↓
・出品画面
　・ISBN
　・名古屋大学、南山大学、その他（parent）
　・学部,カテゴリ（child）
　↓
・確認画面（modal）
　・本のタイトル（ISBNから取得）
　・画像（ISBNから取得）
　・Yeｓ、No

**Comment by TakenokoTech** [comment]
これ、Texserverのview使っても実現出来るけど、どっちが良いのかな

Texserver → CakePHPの認証を使って管理者権限付与？
Texclient → 読み込んだものをSuperAgentでAPI叩いてISBNと認証キーを渡す？

**Comment by andychan94** [comment]
Texserver → CakePHPの認証を使って管理者権限付与
に、いたしましょう！

**Comment by TakenokoTech** [comment]
ノディに賛成ー！

**Comment by TakenokoTech** [comment]
これで、セキュリティ面はバッチリだね！

**Comment by TakenokoTech** [comment]
## 参考しりょー

### スマホのブラウザから写真取得 [ File API ]

HTML5標準機能

### バーコードリーダー[ https://github.com/EddieLa/JOB ]

スマホとPCを上手く連動させたい

### 写真のディレクトリに保存[http://app-review.poox.xyz/archives/1289]

サムネイル用に小さい画像も用意すると良いかも（あくまでDB管理の為に）

**Comment by hatimitusiropp** [comment]
ありがたや

**Comment by TakenokoTech** [comment]
管理用はサーバー側で組むのでクローズしときまーす。
