### ISSUE TITLE
ファイル構造を決める

### ISSUE THREAD

**Issue by hatimitusiropp** [tekuppi1/texclient#5]

**Comment by TakenokoTech** [comment]
一旦、現時点で想定している資材をまとめますね。

## サーバー
- img - 本の画像ファイル一式
- src - DB接続用モジュール等

## クライアント
- img - コンテンツ画像(ロゴやら背景画像やら)
- page - ルート配下のHTMLファイル
- js - Javascriptファイル
- css - スタイルシート
- index.html - 一旦、クライアントが見れる唯一のファイル

**Comment by TakenokoTech** [comment]
今のところ考えてる構成は、

<pre>
www/
　- texchage_main/
　　┠ texclient/
　　┃　┠ src/
　　┃　┃　┠ css/
　　┃　┃　┠ js/
　　┃　┃　└ page/
　　┃　┠ img/
　　┃　┠ build/　(圧縮したファイル達←自動生成)
　　┃　┠ mock/　(サーバー接続のテスト用環境)
　　┃　┠ .git
　　┃　┠ .htaccess　(このファイルでエンドポイント(直ジャンプ出来るURL)をindex.htmlにするよ)
　　┃　└ index.html
　　└ texserver/
　　　　┠ (ここは多分cakePHPのファルダ一式？)
　　　　┠ img/
　　　　┠ .git
　　　　└ .htaccess
</pre>

こんな感じ。

**Comment by TakenokoTech** [comment]
完璧に同じじゃないけど(不足があるかな)、クライアントの開発組が触れられるファイルはsrc内位かな

**Comment by TakenokoTech** [comment]
## クライアント環境も一応整理しまぁす

規格
- html5
- SCSS (cssと同じ感じ)
- ECMASCript2015(JavaScriptの最新版)

ライブラリ
- AngularJS
- Bootstrap (3 or 4)
- material for Bootstrap
- SuperAgent
- jQuery
- Materialize

ビルド環境
- node.js
- Gulp.js

### リンク
- AngularJS [http://www.tohoho-web.com/ex/angularjs.html]()
- ECMASCript2015(es2015) [http://qiita.com/tuno-tky/items/74ca595a9232bcbcd727]()
- Bootstrap 4 [http://qiita.com/youthkee/items/e9e105e35526f908f48a]()
- Material Design for Bootstrap [http://fezvrasta.github.io/bootstrap-material-design/]()
- Materialize [http://materializecss.com/]()

**Comment by TakenokoTech** [comment]
フレームワーク組んだので、クローズしますー。
