### ISSUE TITLE
運営さん用のページにログインするために使う統合認証基盤とは？

### ISSUE THREAD

**Issue by hatimitusiropp** [tekuppi1/texclient#6]

**Comment by hatimitusiropp** [comment]
アカウントは運営さん用のやつ一つだけです。

運営さん用のページでやりたい事
- [ ] 受け取り期限を過ぎた予約のキャンセル
- [ ] 現在予約されている本の確認
- [ ] 予約が完了した本の在庫の冊数を減らす（予約取引完了）
- [ ] 古本市でもらわれていった本の在庫の冊数を減らす（取引完了）
  →ここでも本の検索が必要になる

**Comment by TakenokoTech** [comment]
一旦はコントローラ部分を作るときに決めましょ

**Comment by TakenokoTech** [comment]
認証有りの管理ページはサーバー側に寄せる方向なのでクローズしまーす。
